### ISSUE TITLE
How to store strings?

### ISSUE THREAD

**Issue by ChristophStanik** [MusesProject/MusesClientWindows#3]
We need to think about how and where we want to store string messages

**Comment by yasali** [comment]
You mean and alternative to strings.xml file of android?

**Comment by ChristophStanik** [comment]
yes. A place where we collect all the strings that we need.

**Comment by yasali** [comment]
I am currently using a file named LabelsAndText with static final fields. this or similar file can be used, give your thoughts.

**Comment by ChristophStanik** [comment]
fine for me
